import { StyleSheet, Dimensions } from "react-native";
import { Theme } from "../Theme";
import { widthPercentageToDP as wp, heightPercentageToDP as hp } from "react-native-responsive-screen";

export const estilo = StyleSheet.create({
  containerTarjetaBlanca: {
    height:hp('40%'),
    width:wp('90%'),
    backgroundColor: Theme.Blanco,
    borderRadius: 10,
    alignSelf: "center",
    top:hp('10%')
    // top: Dimensions.get("window").height / 8,
    // width: Dimensions.get("window").width / 1.1,
    // height: Dimensions.get("window").height / 2.7,
  },
  imagenFotoVertical: {
    height:hp('16%'),
    width:wp('31%'),
    position:"absolute",
    borderRadius: 4,
    alignSelf:'center',
    bottom:hp('10%'),
    left:wp('55%'),
    // height: Dimensions.get("window").width / 3.2,
    // top: Dimensions.get("window").height / 8.7,
    // left:Dimensions.get("window").height / 3.67, 
    // width: Dimensions.get("window").height / 6.5,
  },
  loguito: {
    height:hp('10%'),
    alignSelf: "center",
    position: "absolute",
    bottom:hp('10%')
    // bottom: -Dimensions.get("window").height / 35,
    // height: Dimensions.get("window").height / 5,
  },
  expiradoContainer: {
    marginTop: 20,
    width: "100%",
    padding: 13,
    alignItems: "center",
    alignSelf: "center",
    borderRadius: 5,
    backgroundColor: Theme.Rojo,
  },
  imagenFotoHorizontal: {
    height:hp('16%'),
    width:wp('32%'),
    borderRadius: 4,
    position:"absolute",
    top:hp('12%'),
    left:hp('30%'),
    // width: Dimensions.get("window").height / 6.5,
    // height: Dimensions.get("window").width / 3.2,
    // top: Dimensions.get("window").height / 8.7,
    // left:Dimensions.get("window").height / 3.67, 
  },
  containerLandscape: {
    height:hp('35%'),
    width:wp('100%'),
    // height: Dimensions.get("window").height / 3,
    // width: Dimensions.get("window").width / 1.1,
    backgroundColor: Theme.Blanco,
    borderRadius: 10,
    alignSelf: "center",
    top:hp('3%'),
    // top: Dimensions.get("window").height / 20,
  },
  linea: {
    height: 2,
    width: "100%",
    backgroundColor: "black",
    marginVertical: 15,
    bottom: 35,
  },

  revezVertical: {
    flex:1,
    height:hp('60%'),
    width:wp('90%'),
    resizeMode: "contain",
    alignSelf: "center",
    // height: Dimensions.get("window").height / 3.3,
    // width: "100%",
    // top: Dimensions.get("window").height / 60,
    // backgroundColor: Theme.Blanco,
  },
  revezHorizontal: {
    flex:1,
    height:hp('50%'),
    width: wp('90%'),
    resizeMode: "contain", 
    justifyContent:'center',
    alignSelf: "center",
    // top: Dimensions.get("window").height / 60,
    // backgroundColor: Theme.Blanco,
    // height: Dimensions.get("window").height / 3.3
  },
  row: {
    // left: 10,
    left:wp('2%'),
    flex: 1,
    padding: 0,
    flexDirection: "row",
    justifyContent: "space-evenly",
    rowGap: 3,
    flexWrap: "wrap",
    position: "absolute",
    width:wp('100%')
    // top: Dimensions.get("window").height / 8,
    // width: Dimensions.get("window").width / 1,
  },
  rowLandscape: {
    left: 10,
    flex: 1,
    padding: 0,
    flexDirection: "row",
    justifyContent: "space-evenly",
    rowGap: 3,
    flexWrap: "wrap",
    position: "absolute",
    top: Dimensions.get("window").height / 4,
    width: Dimensions.get("window").width / 1,
  },
  textoResaltado: {
    fontSize: 14,
    fontWeight: "bold",
    flexGrow: 5,
    height:hp('25%'),
    width:wp('10%')
    // height: 25,
    // width: 100,
  },
  textoNormal: {
    fontSize: 12,
    flexGrow: 5,
    height:hp('25%'),
    width:wp('10%'),
    // height: 25,
    // width: 100,
  },
  containerHeader: {
    height:hp('50%'),
    width:wp('10%'),
    top:hp('70%'),
    flex: 2,
    flexDirection: "row",
    position: "absolute",
    zIndex: 2,
    // height: Dimensions.get("window").height / 49.99,
    // width: Dimensions.get("window").width / 1.2,
    // top: 70,
  },
  amtarTitulo: {
    alignSelf: "flex-end",
    fontSize:hp('6%'),
    zIndex: 2,
    position: "absolute",
    // fontSize: Dimensions.get("window").height / 15,
  },
  imagen: {
    height: hp('10%'),
    width:wp('10%'),
    // height: Dimensions.get("window").height / 12,
    // width: Dimensions.get("window").width / 5.4,
    // right: Dimensions.get("window").width / 55,
  },
  amtarSubTitulo: {
    alignSelf: "flex-end",
    bottom:hp('2.5%'),
    fontWeight: "bold",
    // bottom: 25,
  },
  dorado: {
    color: Theme.Dorado,
  },
});
