import { StyleSheet, Dimensions } from "react-native";
import { Theme } from "../Theme";
export const estilo = StyleSheet.create({
  containerTarjetaBlanca: {
    height: Dimensions.get("window").height / 2.7,
    width: Dimensions.get("window").width / 1.1,
    backgroundColor: Theme.Blanco,
    borderRadius: 10,
    alignSelf: "center",
    top: Dimensions.get("window").height / 8,
  },
  imagenFotoVertical: {
    width: Dimensions.get("window").height / 6.5,
    height: Dimensions.get("window").width / 3.2,
    borderRadius: 4,
    top: Dimensions.get("window").height / 8.7,
    left:Dimensions.get("window").height / 3.67, 
    position:"absolute",
  },
  loguito: {
    height: Dimensions.get("window").height / 5,
    alignSelf: "center",
    position: "absolute",
    bottom: -Dimensions.get("window").height / 35,
  },
  expiradoContainer: {
    marginTop: 20,
    width: "100%",
    padding: 13,
    alignItems: "center",
    alignSelf: "center",
    borderRadius: 5,
    backgroundColor: Theme.Rojo,
  },
  imagenFotoHorizontal: {
    width: Dimensions.get("window").height / 6.5,
    height: Dimensions.get("window").width / 3.2,
    borderRadius: 4,
    top: Dimensions.get("window").height / 8.7,
    left:Dimensions.get("window").height / 3.67, 
    position:"absolute",
  },
  containerLandscape: {
    height: Dimensions.get("window").height / 3,
    width: Dimensions.get("window").width / 1.1,
    backgroundColor: Theme.Blanco,
    borderRadius: 10,
    alignSelf: "center",
    top: Dimensions.get("window").height / 20,
  },
  linea: {
    height: 2,
    width: "100%",
    backgroundColor: "black",
    marginVertical: 15,
    bottom: 35,
  },

  revezVertical: {
    height: Dimensions.get("window").height / 3.3,
    width: "100%",
    resizeMode: "contain",
    top: Dimensions.get("window").height / 60,
    backgroundColor: Theme.Blanco,
    alignSelf: "center",
  },
  revezHorizontal: {
    height: Dimensions.get("window").height / 3.3,
    width: "100%",
    resizeMode: "contain",
    top: Dimensions.get("window").height / 60,
    backgroundColor: Theme.Blanco,
    alignSelf: "center",
  },
  row: {
    left: 10,
    flex: 1,
    padding: 0,
    flexDirection: "row",
    justifyContent: "space-evenly",
    rowGap: 3,
    flexWrap: "wrap",
    position: "absolute",
    top: Dimensions.get("window").height / 8,
    width: Dimensions.get("window").width / 1,
  },
  rowLandscape: {
    left: 10,
    flex: 1,
    padding: 0,
    flexDirection: "row",
    justifyContent: "space-evenly",
    rowGap: 3,
    flexWrap: "wrap",
    position: "absolute",
    top: Dimensions.get("window").height / 4,
    width: Dimensions.get("window").width / 1,
  },
  textoResaltado: {
    fontSize: 14,
    fontWeight: "bold",
    flexGrow: 5,
    height: 25,
    width: 100,
  },
  textoNormal: {
    fontSize: 12,
    flexGrow: 5,
    height: 25,
    width: 100,
  },
  containerHeader: {
    height: Dimensions.get("window").height / 49.99,
    width: Dimensions.get("window").width / 1.2,
    top: 70,
    flex: 2,
    flexDirection: "row",
    position: "absolute",
    zIndex: 2,
  },
  amtarTitulo: {
    alignSelf: "flex-end",
    fontSize: Dimensions.get("window").height / 15,
    zIndex: 2,
    position: "absolute",
  },
  imagen: {
    height: Dimensions.get("window").height / 12,
    width: Dimensions.get("window").width / 5.4,
    right: Dimensions.get("window").width / 55,
  },
  amtarSubTitulo: {
    alignSelf: "flex-end",
    bottom: 25,
    fontWeight: "bold",
  },
  dorado: {
    color: Theme.Dorado,
  },
});
