import { StyleSheet, Dimensions } from "react-native";
import { Theme } from "../Theme";

export const estilo = StyleSheet.create({
  fondo: {
    backgroundColor: Theme.Dark,
    height: "100%",
  },
  cuadradoFoto: {
    width: 200,
    height: 200,
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "row",
    position: "absolute",
    alignSelf: "center",
    borderRadius: 100,
    marginTop: 10,
    backgroundColor: "#282828",
    borderColor: Theme.Dorado,
    borderWidth: 3,
  },
  botonFoto: {
    alignItems: "center",
    justifyContent: "center",
    alignSelf: "center",
    paddingVertical: 12,
    paddingHorizontal: 32,
    borderRadius: 4,
    elevation: 3,
    backgroundColor: Theme.Dorado,
    top: Dimensions.get("window").height / 3.5,
    width: Dimensions.get("window").width / 2,
  },
  fotoText: {
    fontSize: 16,
    lineHeight: 21,
    letterSpacing: 0.25,
    fontWeight: "bold",
    color: "black",
  },
  email: {
    alignSelf: "center",
    top: Dimensions.get("window").height / 2.5,
    backgroundColor: "red",
  },
  containerEmail: {
    height: Dimensions.get("window").height / 15,
    width: Dimensions.get("window").width / 1.2,
    padding: 13,
    alignItems: "center",
    alignSelf: "center",
    justifyContent: "center",
    borderRadius: 15,
    backgroundColor: Theme.Blanco,
  },
  containerContra: {
    height: Dimensions.get("window").height / 15,
    padding: 13,
    width: Dimensions.get("window").width / 1.2,

    alignItems: "center",
    alignSelf: "center",
    justifyContent: "center",
    borderRadius: 15,
    backgroundColor: Theme.Blanco,
  },
  containerContraConfir: {
    height: Dimensions.get("window").height / 15,
    padding: 13,
    width: Dimensions.get("window").width / 1.2,

    alignItems: "center",
    alignSelf: "center",
    justifyContent: "center",
    borderRadius: 15,
    backgroundColor: Theme.Blanco,
  },
  contarinerTelefono: {
    height: Dimensions.get("window").height / 15,
    padding: 13,
    width: Dimensions.get("window").width / 1.2,

    alignItems: "center",
    alignSelf: "center",
    justifyContent: "center",
    borderRadius: 15,
    backgroundColor: Theme.Blanco,
  },
  botonIniciar: {
    height: Dimensions.get("window").height / 15,
    width: Dimensions.get("window").width / 1.2,
    padding: 13,
    alignItems: "center",
    alignSelf: "center",
    borderRadius: 15,
    backgroundColor: Theme.Dorado,
  },
  contraseñaText: {
    color: Theme.Blanco,
    alignSelf: "center",
    bottom: -Dimensions.get("window").height / 3.7,
  },
  confirmarContraseñaText: {
    color: Theme.Blanco,
    alignSelf: "center",
    bottom: -Dimensions.get("window").height / 3.5,
  },
  emailText: {
    color: "black",
    top: Dimensions.get("window").height / 4.2,
    alignSelf: "center",
  },
  placeHolderEmail: {
    backgroundColor: "#A6A6A6",
    width: "95%",
    borderRadius: 5,
    textAlign: "center",
  },
  placeHolderContra: {
    backgroundColor: "#A6A6A6",
    width: "95%",
    borderRadius: 5,
    textAlign: "center",
  },
  placeHolderTel: {
    backgroundColor: "#A6A6A6",
    width: "95%",
    borderRadius: 5,
    textAlign: "center",
  },
  crearText: {
    fontWeight: "bold",
    color: "black",
    fontSize: 16,
    lineHeight: 21,
    letterSpacing: 0.25,
  },
  checkbox:{
    height: Dimensions.get("window").height / 90,
    padding: 13,
    width: Dimensions.get("window").width / 70,
    borderRadius: 15,
    backgroundColor: Theme.Blanco,
    bottom:Dimensions.get('window').height/6.7,
    right:Dimensions.get('window').width/12,
  },
  checkBoxView: {
    height: Dimensions.get("window").height / 15,
    bottom:Dimensions.get('window').height/7,
    alignItems: "center",
    alignSelf: "center",
    justifyContent: "center",
   
  }
});
